apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: trackunit
  labels:
    app.kubernetes.io/name: httpbin
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: httpbin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: httpbin
    spec:
      serviceAccountName: trackunit
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status/200
              port: http
          readinessProbe:
            httpGet:
              path: /status/200
              port: http
